# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 20:12
from __future__ import unicode_literals

import caching.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkpearl_lodestone', '0002_auto_20151214_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('clan_1', models.CharField(max_length=50)),
                ('clan_2', models.CharField(max_length=50)),
            ],
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.AddField(
            model_name='character',
            name='clan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='linkpearl_lodestone.Race'),
        ),
    ]
