# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 23:47
from __future__ import unicode_literals

import caching.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkpearl_lodestone', '0005_auto_20151214_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('short', models.CharField(max_length=10)),
            ],
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.AddField(
            model_name='character',
            name='gc_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='gc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='linkpearl_lodestone.GrandCompany'),
        ),
    ]
