# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkpearl_lodestone', '0006_auto_20151214_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodestone_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='grandcompany',
            options={'verbose_name_plural': 'grand companies'},
        ),
        migrations.AlterField(
            model_name='character',
            name='gc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='linkpearl_lodestone.GrandCompany', verbose_name='Grand Company'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gc_rank',
            field=models.IntegerField(default=0, verbose_name='Grand Company Rank'),
        ),
        migrations.AddField(
            model_name='character',
            name='fc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='linkpearl_lodestone.FreeCompany', verbose_name='Free Company'),
        ),
    ]
