# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkpearl_lodestone', '0007_auto_20151215_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freecompany',
            options={'verbose_name_plural': 'free companies'},
        ),
        migrations.AlterField(
            model_name='character',
            name='lodestone_id',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='freecompany',
            name='lodestone_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
