# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkpearl_lodestone', '0008_auto_20151215_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
