# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 13:45
from __future__ import unicode_literals

import caching.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkpearl_lodestone', '0009_auto_20151215_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(blank=True, max_length=3)),
            ],
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('exp_at', models.IntegerField()),
                ('exp_of', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkpearl_lodestone.Character')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkpearl_lodestone.Job')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='jobs',
            field=models.ManyToManyField(through='linkpearl_lodestone.Level', to='linkpearl_lodestone.Job'),
        ),
    ]
