# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 15:04
from __future__ import unicode_literals

import caching.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkpearl_lodestone', '0010_auto_20151215_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Mount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.AddField(
            model_name='character',
            name='minions',
            field=models.ManyToManyField(related_name='characters', to='linkpearl_lodestone.Minion'),
        ),
        migrations.AddField(
            model_name='character',
            name='mounts',
            field=models.ManyToManyField(related_name='characters', to='linkpearl_lodestone.Mount'),
        ),
    ]
