# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkpearl_lodestone', '0013_auto_20151215_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='linkpearl_lodestone.Title'),
        ),
    ]
