# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkpearl_lodestone', '0014_auto_20151217_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='lodestone_id',
            field=models.IntegerField(unique=True),
        ),
    ]
